### ISSUE TITLE
ValueError: Unhandled pending operations for models

### ISSUE THREAD

**Issue by chapayevdauren** [django-getpaid/django-getpaid#104]
Hi, I have this error when to try makemigrations command

```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 132, in handle
    migration_name=self.migration_name,
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 46, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 131, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 166, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/home/dauren/Work/Django-Projects/khat/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 235, in __init__
    raise ValueError(self._pending_models_error(pending_models))
ValueError: Unhandled pending operations for models:
  orders.order (referred to by fields: getpaid.Payment.order)

```

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Versions 1.x are no longer supported.
