### ISSUE TITLE
makemigrations doesn't work for 1.10.5

### ISSUE THREAD

**Issue by donvito-pl** [django-getpaid/django-getpaid#109]
Hi. After following the tutorial precisely, I am getting stuck with the following error.
Hmm, what steps might be missing?!

Declared with a dummy backend and/or przelewy24.pl

python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/makemigrations.py", line 149, in handle
    loader.project_state(),
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 317, in project_state
    return self.graph.make_state(nodes=nodes, at_end=at_end, real_apps=list(self.unmigrated_apps))
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/graph.py", line 409, in make_state
    project_state = self.nodes[node].mutate_state(project_state, preserve=False)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/operations/models.py", line 281, in state_forwards
    apps = state.apps
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/state.py", line 176, in apps
    return StateApps(self.real_apps, self.models)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/state.py", line 249, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field getpaid.Payment.order was declared with a lazy reference to 'portal.order', but app 'portal' doesn't provide model 'order'.

**Comment by donvito-pl** [comment]
The workaround for this issue is to migrate without the getpaid app enabled (to create the order schema), Then enabling it back on and migrate again.

**Comment by dekoza** [comment]
Documentation will be reviewed and updated for upcoming 1.8 release. Sorry for inconvenience.

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Versions 1.x are no longer supported.
