### ISSUE TITLE
Django 3.1.2 / Python 3.7.8 -> ImportError: cannot import name 'classproperty' from 'django.utils.decorators'

### ISSUE THREAD

**Issue by louisdupreve** [django-getpaid/django-getpaid#152]
* django-getpaid version: last one
* Django version: 3.1.2
* Python version: 3.7.8
* Operating System: Cpanel (Mysql) 

### Description

```
Traceback (most recent call last):
  File "/opt/alt/python37/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/alt/python37/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/exemple/virtualenv/FC/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/getpaid/__init__.py", line 1, in <module>
    from .types import FraudStatus, PaymentStatus
  File "/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/getpaid/types.py", line 6, in <module>
    from django.utils.decorators import classproperty
ImportError: cannot import name 'classproperty' from 'django.utils.decorators' (/home/exemple/virtualenv/FC/3.7/lib/python3.7/site-packages/django/utils/decorators.py)
```

**Comment by sdarmofal** [comment]
It's a problem with import in `getpaid/types.py`. I saw that it's fixed on branch master, but not released yet.

**Comment by sdarmofal** [comment]
@dekoza Can you take a look?

**Comment by dekoza** [comment]
Yeah, sorry for the delay.

**Comment by matifly94** [comment]
@dekoza What is holding the release to pip?

**Comment by sdarmofal** [comment]
@dekoza Still waiting. Do you need any help?

**Comment by dekoza** [comment]
Done.
