### ISSUE TITLE
django-getpaid won't migarte in new project 

### ISSUE THREAD

**Issue by BuSSioR** [django-getpaid/django-getpaid#154]
* django-getpaid version: 2.2.2
* Django version: 3.2.3
* Python version: 3.8
* Operating System: macOS

### Description

As I've created new project and I wanted to use django-getpaid I've just installed it with poetry, defined an Order instance and tried to migrate the app.

Result: 
```bash
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 172, in handle
    changes = autodetector.changes(
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 41, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 126, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/state.py", line 212, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/state.py", line 277, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field getpaid.Payment.order was declared with a lazy reference to 'backend.order', but app 'backend' doesn't provide model 'order'.
```
Definition of an Order model:
```python
class Order(AbstractOrder):
    items = models.ManyToManyField("Product", related_name='items', through="OrderItem")
    description = models.CharField(max_length=128)
    buyer_email = models.EmailField()
    buyer_phone = models.CharField(max_length=12)

    def is_ready_for_payment(self):
        pass

    def get_total_amount(self):
        final = Decimal(0)

        for order_item in self.items.all():
            final += order_item.item.final_price_with_tax * order_item.amount
        return final

    def get_buyer_info(self):
        return {"email": self.buyer_email, "phone": self.buyer_phone}

    def get_currency(self):
        return "PLN"

    def get_description(self):
        return self.description
```
settings.py:
```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'getpaid',
    'getpaid_payu',  # one of plugins
    'rest_framework',
    'backend.apps.BackendConfig',
    'corsheaders',
]
GETPAID_ORDER_MODEL = 'backend.Order'
GETPAID_BACKEND_SETTINGS = {
    "getpaid_payu": {
        # take these from your merchant panel:
        "pos_id": os.getenv('PAYU_POS_ID'),
        "second_key": os.getenv("PAYU_SECOND_KEY"),
        "oauth_id": os.getenv('PAYU_OAUTH_ID'),
        "oauth_secret": os.getenv("PAYU_OAUTH_SECRET"),
    },
}
```
#### Recreate an database and migrations
Result: Fail, django-getpaid requires at least one migration to run.
Traceback
```bash
$ python manage.py migrate backend 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/loader.py", line 259, in build_graph
    self.graph.validate_consistency()
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/drop-OdaMbioT-py3.8/lib/python3.8/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration getpaid.0001_initial dependencies reference nonexistent parent node ('backend', '0001_initial')
```
#### Core code modifications
Result: success, but after following steps:
1. I've commented these lines in `getpaid/models.py`
```python

class Payment(AbstractPayment):
    class Meta(AbstractPayment.Meta):
        swappable = swapper.swappable_setting("getpaid", "Payment")
```
after what I've received 
```bash
RuntimeError: Model class getpaid.models.Payment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
so I've commented `get_paid` in `INSTALLED_APPS`

2. Migrate my app once, so I have an Order in my schema
3. Uncomment the Payment model in the app and `getpaid` in `INSTALLED_APPS`
4. Migrated it once again.

### Summary
Actually I'm not sure if I did not broke something, I'll update you guys after some tests, but anyway, did I do something wrong? I actually followed the documentation, so If it's my fault maybe docs update should be considered? 

Have great day,
Mat.

**Comment by dekoza** [comment]
Looks very interesting. Can you provide a stripped-down repo that shows the problem? It will be much easier for me to debug. Or maybe you'd be able to provide a test for this? Anyway thanks for reporting, I'll take a look asap.

**Comment by dekoza** [comment]
OK, first of all I need to fix migrations because `backend` should not be present there.

**Comment by dekoza** [comment]
[Please disregard my previous ~deleted~ comments :wink: ]

Thanks for reporting!

It looks like your `backend` app does not have any migrations yet. The initial migration from `getpaid` looks like this:

```python
def get_dependencies():
    app_name, _, model_name = swapper.get_model_name("getpaid", "Order").rpartition(".")
    return [(app_name, "0001_initial")]
```

It looks into your settings for the Order model and pretty much locks itself to the initial migration of the app that defines that model. It is necessary for FK relations.

You may have found a spot where the documentation is lacking. Indeed you first need to make migration for your app and only **then** add `getpaid` to `INSTALLED_APPS` :thinking: I need to find a clever solution to this as I feel this might be too much hassle :wink:

**Comment by BuSSioR** [comment]
Hi @dekoza  thanks for blazing fast response! The thing is that even with initial migration it does not goes through. Check this example repo: https://github.com/BuSSioR/getpaid_issue_example/
After `python manage.py migrate` it throws:
```bash
$ python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
getpaid.Payment.order: (fields.E300) Field defines a relation with model 'test_project.Order', which is either not installed, or is abstract.
getpaid.Payment.order: (fields.E307) The field getpaid.Payment.order was declared with a lazy reference to 'test_project.order', but app 'test_project' doesn't provide model 'order'.
```

and `show_migrations` after I comment `get_paid` from `INSTALLED APPS` and `MyCustomOrder` shows that every other migration is in place
```bash
$ python manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
sessions
 [X] 0001_initial
test_project
 [X] 0001_initial
```

**Comment by dekoza** [comment]
OK, I'll use your `test_project` to investigate it further. Thanks!

**Comment by dekoza** [comment]
I tried using your test_project but something strange is going on when `swapper` tries to import the model (it looks for lowercase class name for some reason :open_mouth: ) and I need to dig a bit deeper.

For now I changed how the dependencies in migration are determined by using `swapper`'s method. This change is in repo, so you can test it by using `django-getpaid = { git = "https://github.com/django-getpaid/django-getpaid" }` inside your `pyproject.toml`

**Comment by dekoza** [comment]
I can't replicate this issue fully when creating new project by the book. I can only confirm that you cannot create initial migration for the app providing custom Order model when `getpaid` is in `INSTALLED_APPS` and that requires docs update and a patch (if possible) but it's a different story.

What I did:

0. Initialize poetry project, add django and django-getpaid
1. Create blank django project using `django-admin startproject example`
2. Create a new app inside the project: `cd example && django-admin startapp myapp`, add `myapp` to `INSTALLED_APPS`
3. Create `CustomOrder` model that inherits from `models.Model`
4. Run `manage.py makemigrations`
5. Add `getpaid` to `INSTALLED_APPS`, change the parent class of `CustomOrder` to `getpaid.models.AbstractOrder`
6. Run `manage.py migrate`

This is the result of steps 1-5: https://github.com/dekoza/getpaid-example
It should pass step 6 without issues.

Please let me know how it went on your side and what do you think about this.

**Comment by dekoza** [comment]
OK, I think I've found a way to do a proper project creation. I've refactored `getpaid` a bit and updated the installation docs: https://django-getpaid.readthedocs.io/en/latest/installation.html

**Comment by dekoza** [comment]
@BuSSioR can you confirm if this issue is fixed on your side?
